import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import "boxicons/css/boxicons.css"
import HeroLayout from "@/components/layouts/Hero"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]/route"
import SessionProvider from "@/components/layouts/Session"

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <SessionProvider session={session}>
          <HeroLayout>{children}</HeroLayout>
        </SessionProvider>
      </body>
    </html>
  )
}
