import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import "boxicons/css/boxicons.css"
import HeroLayout from "@/components/layouts/Hero"
//
const poppins = Poppins({
  weight: ["400", "500", "700"], // You can select multiple font weights
  subsets: ["latin"] // Specify the subset
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <HeroLayout>{children}</HeroLayout>
      </body>
    </html>
  )
}
